### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by ghost** [Cartman720/PySitemap#5]
I get this:

```
Parsing http://canterano.somenxavier.xyz/trobar-mesures-figures-vnps/figures-1.ggb
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    links = crawler.start()
  File "/home/xan/Baixades/sitemap/PySitemap-master/crawler.py", line 17, in start
    self.crawl(self.url)
  File "/home/xan/Baixades/sitemap/PySitemap-master/crawler.py", line 49, in crawl
    self.crawl(urljoin(self.url, link))
  File "/home/xan/Baixades/sitemap/PySitemap-master/crawler.py", line 49, in crawl
    self.crawl(urljoin(self.url, link))
  File "/home/xan/Baixades/sitemap/PySitemap-master/crawler.py", line 49, in crawl
    self.crawl(urljoin(self.url, link))
  [Previous line repeated 20 more times]
  File "/home/xan/Baixades/sitemap/PySitemap-master/crawler.py", line 26, in crawl
    response = urllib.request.urlopen(url)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

after  python main.py --url="http://canterano.somenxavier.xyz"

**Comment by wubinbai** [comment]
I Have same issue on https://pytorch.org
